services:
  - type: web
    name: telegram-downloader-bot
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: BOT_TOKEN
        sync: false # حتماً توکن را در پنل Render وارد کنید، اینجا ننویسید
