services:
  - type: web
    name: telegram-downloader-bot
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # مقدار را از داشبورد Render وارد کنید
      - key: PORT
        value: "8000"
